apiVersion: v1 
kind: Pod 
metadata: 
  name: empty-dir-pod 
spec: 
  restartPolicy: Never 
  containers: 
    - image: busybox 
      name: empty-pod 
      command: ['sh', '-c', 'while true; do echo Scceessfully inserted data > /output/output.txt; sleep 5; done']
      volumeMounts: 
        - name: my-volume
          mountPath: /output 
    - image: busybox 
      name: empty-pod-1 
      command: ['sh', '-c', 'while true; do echo Scceessfully Completed DevOps Training > /input/output.txt; sleep 5; done']
      volumeMounts:
        - name: my-volume
          mountPath: /input
  volumes:
    - name: my-volume 
      emptyDir: {}