apiVersion: v1 
kind: Pod 
metadata: 
  name: volume-pod 
spec: 
  restartPolicy: Never
  containers:
    - image: busybox
      name: host-volume
      command: ['sh', '-c', 'echo Sucessfully completed k8s Training > /output/output.txt']
      volumeMounts:
        - name: my-example 
          mountPath: /output 
  volumes: 
    - name: my-example 
      hostPath: 
        path: /var/data     
