apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: web-murali
  template:
    metadata:
      labels:
        app: web-murali 
    spec:
      containers:
      - name: app-web
        image: muralisocial123/web-app-test:latest
        ports:
        - containerPort: 80
      nodeSelector:
        app: web-app 
