apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-deployment-example
spec:
  selector:
    matchLabels:
      web: example
  template:
    metadata:
      labels:
        web: example
    spec:
      containers:
      - name: node-port
        image: muralisocial123/web-app-test:latest
        ports:
        - containerPort: 80
