apiVersion: v1
kind: Pod
metadata:
  name: web-example
  labels:
    name: node
spec:
  containers:
  - name: sample-web
    image: muralisocial123/s4-web-app:1.0
    ports:
      - containerPort: 80
  - name: node-example
    image: muralisocial123/node-app-example:latest
    ports: 
      - containerPort: 3000    
