apiVersion: v1
kind: ReplicationController
metadata:
  name: node-example-rc
spec:
  template:
    metadata:
      name: node-app 
      labels: 
        app: web 
    spec: 
      containers:
        - name: node-app-web 
          image: muralisocial123/node-app-example:latest
          ports: 
            - containerPort: 3000
  replicas: 3 
  selector: 
      app: web          
  
