apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: my-volume 
            mountPath: /data  
      volumes: 
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc
