apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      web: example
  template:
    metadata:
      labels:
        web: example
    spec:
      containers:
      - name: web-app
        image: muralisocial123/web-app-test:latest
        ports:
        - containerPort: 80
